using `tonic` in  place of `spikedata`
* adapted notebooks to use tonic instead of the deprecated `spikedata` module

* added a `DATADIR` variable to let user choose their data directory (`/tmp` has the nice property of getting easily flushed..)

*  fixed an error to a call of a deprecated torch function: `AttributeError: module 'torch' has no attribute '_six'`

* removed all outputs to reduce size of notebooks